in_hippunfold: /local/scratch/ds002168_hippunfold_magick_T2w

in_bids: /local/scratch/ds002168

fs_subfields: /local/scratch/ds002168_freesurfer/sub-{subject}/mri/{hemi}.hippoAmygLabels-T2.v21.FS60.mgz
fs_xfm_t1_t2: /local/scratch/ds002168_freesurfer/sub-{subject}/mri/transforms/T1_to_T2.v21.lta

subjects:
  - 1425

subfield_label_list: freesurfer_labellist.txt
maxprob_label_list: maxprob_labellist.txt


ref_surf_unfold: /localscratch/hippunfold/hippunfold/resources/unfold_template_hipp/tpl-avg_space-unfold_den-{density}_midthickness.surf.gii
